version: "3.8"
services:
  app:
    image: mynamenn/task-management-ui:latest
    ports:
      - 3000:3000
  server:
    image: mynamenn/task-processing-backend:latest
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - prisma-network
    environment:
      PORT: 8000
      NODE_ENV: production
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydatabase?schema=public"
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase

networks:
  prisma-network:
    name: prisma-network

volumes:
  pgdata:
